meta:
    type: "mysql"
    sqlite: "./data/schema-euler.db"
    mysql:
        host: "127.0.0.1"
        port: "3306"
        db: "eulerdb_schema"
        user: "root"
        passwd: "123456"

back_db:
    type: "mysql"
    mysql:
        host: "127.0.0.1"
        port: "3306"
